version: '3.7'

services: 
  nginx: 
    build: 
      context: ./nginx
    container_name: nginx
    restart: always
    ports: 
      - 8080:80
    networks:
      - nodenet
  
  app:
    build:
      context: ./app
    container_name: app
    restart: always
    networks:
      - nodenet
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: db
    restart: always
    tty: true
    networks:
      - nodenet
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./db/scripts/script-user.sql:/docker-entrypoint-initdb.d/1.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

networks: 
  nodenet:
    driver: bridge